### ISSUE TITLE
How should I build and Use this Project?

### ISSUE THREAD

**Issue by gnanakeethan** [micwallace/WebPrint-Android#1]
I have worked on POS printers before, I am just trying to implement the functionality via Android to bluetooth based printers. 

How should the project be built and used to print from a website using an android phone to a bluetooth based printer?

**Comment by micwallace** [comment]
There's no support for bluetooth printers at the moment but you could add it.

**Comment by gnanakeethan** [comment]
I am not an Android expert. I have seen some apps which implement bluetooth printing functionality. It will be better if there is something that can transparently act as a proxy for the underlying printer. 

How much is this possible? I have been searching for a open source implementation. Have anyone built such a thing already?

**Comment by gnanakeethan** [comment]
Is it possible to print to a wired printer using this framework? If so, How should I use this?

**Comment by micwallace** [comment]
A proxy is exactly what webprint is, so it would be easy to add bluetooth printers. USB connected printers are already supported via a USB OTG compatible phone & adapter.

**Comment by gnanakeethan** [comment]
Is there a guide how I should start using this framework?

**Comment by micwallace** [comment]
If you head over to the main (desktop) webprint project there is javascript code and example to get you started:
https://github.com/micwallace/WebPrint

As for bluetooth support, it depends mainly on what printer models you are using, here's some useful android dev info:
http://stackoverflow.com/questions/9838822/android-bluetooth-printing

**Comment by gnanakeethan** [comment]
However, How should I get the android connection working in proper? 

Should I manually build APK and deploy them? or manually deploy using that builder you placed on readme?

**Comment by gnanakeethan** [comment]
I am so confused on the point, at where should I start setting up everything.

**Comment by micwallace** [comment]
I host the WebPrint Android app in the play store. If you make changes to the Android app (ie, add bluetooth), you could provide the changes to the main project and I will publish them or publish your altered version in the play store separately. 

If you just want to print, all you need to use is the Javascript. Here's an example, view it on Android to see it in action:
https://wallaceit.com.au/webprint/example.html

**Comment by gnanakeethan** [comment]
I got it, How can I identify the printers which support android USB connection? or any printer that is USB connected will work?

**Comment by micwallace** [comment]
Yes any printer supporting ESC/P and a USB connection should work. But make sure your phone supports USB OTG also.

**Comment by gnanakeethan** [comment]
Okay thanks. I will try. Is there any chance that you will include Bluetooth connector?

**Comment by micwallace** [comment]
Maybe one day.
